### ISSUE TITLE
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by ming-ming15** [zhizdev/sparsefusion#19]
What a great job this is!

I have a problem:

I run demo.py and get an output: 
Traceback (most recent call last):
  File "demo.py", line 183, in <module>
    main()
  File "demo.py", line 180, in main
    mp.spawn(fit, nprocs=args.gpus, args=(args,))
  File "/home/xd/.conda/envs/sparsefusion1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/xd/.conda/envs/sparsefusion1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/xd/.conda/envs/sparsefusion1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/xd/.conda/envs/sparsefusion1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/xd/sunxue/sparsefusion/demo.py", line 88, in fit
    distillation_loop(
  File "/home/xd/sunxue/sparsefusion/sparsefusion/distillation.py", line 304, in distillation_loop
    pred_x0, x_noisy, noise, alpha_cumprod = plms_sampler.sample(latents, cond_images=batch_features.expand(-1,-1,-1,-1), use_tqdm=False, return_noise=True, max_thres=max_thres)
  File "/home/xd/.conda/envs/sparsefusion1/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xd/sunxue/sparsefusion/external/plms.py", line 36, in sample
    img, x_noisy, noise, alpha_cumprod = self.plms_sample_loop(
  File "/home/xd/.conda/envs/sparsefusion1/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xd/sunxue/sparsefusion/external/plms.py", line 97, in plms_sample_loop
    outs = self.p_sample(
  File "/home/xd/.conda/envs/sparsefusion1/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xd/sunxue/sparsefusion/external/plms.py", line 136, in p_sample
    _, _, e_t = self.get_model_output(unet, x, t, t_next, cond_images, cond_scale, noise_scheduler, pred_objective, dynamic_threshold)
  File "/home/xd/sunxue/sparsefusion/external/plms.py", line 176, in get_model_output
    pred = unet.forward_with_cond_scale(x, noise_scheduler.get_condition(t), cond_images = cond_images, cond_scale = cond_scale)
  File "/home/xd/sunxue/sparsefusion/external/imagen_pytorch.py", line 224, in get_condition
    return maybe(self.log_snr)(times)
  File "/home/xd/sunxue/sparsefusion/external/imagen_pytorch.py", line 58, in inner
    return fn(x)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

how to solve it?

thank you!

**Comment by boxuLibrary** [comment]
I also encountered this problem. Have you solved it?

**Comment by ming-ming15** [comment]
> I also encountered this problem. Have you solved it?

I'm sorry, it hasn't worked out yet.
